vbc /t:library /r:System.dll Misc.vb
vbc /t:library /r:System.dll,System.Drawing.dll,mscorlib.dll MathUtil.vb
vbc /t:library /r:System.dll,System.Drawing.dll ClassRectMemento.vb
vbc /t:library /r:System.dll,System.Drawing.dll InterfaceRectMemento.vb
vbc /t:library /r:System.dll,System.Drawing.dll,System.Windows.Forms.dll,Misc.dll,MathUtil.dll Rect.vb
vbc /t:library /r:System.dll,System.Drawing.dll,System.Windows.Forms.dll,Misc.dll,MathUtil.dll,Rect.dll,ClassRectMemento.dll ClassRect.vb
vbc /t:library /r:System.dll,System.Drawing.dll,System.Windows.Forms.dll,Misc.dll,MathUtil.dll,Rect.dll,InterfaceRectMemento.dll InterfaceRect.vb
vbc /t:library /r:System.dll,System.Drawing.dll,Misc.dll LineMemento.vb
vbc /t:library /r:System.dll,System.Drawing.dll,System.Windows.Forms.dll,Misc.dll,MathUtil.dll,Rect.dll,LineMemento.dll Line.vb
vbc /t:library /r:System.dll,System.Drawing.dll,System.Windows.Forms.dll,Line.dll PropertyForm.vb
vbc /t:library /r:System.dll,System.Drawing.dll,System.Windows.Forms.dll,Rect.dll InputBox.vb
vbc /t:library /r:System.dll,System.Drawing.dll,System.Windows.Forms.dll,Misc.dll,MathUtil.dll,Rect.dll,ClassRect.dll,InterfaceRect.dll,ClassRectMemento.dll,InterfaceRectMemento.dll,Line.dll,LineMemento.dll,InputBox.dll DrawArea.vb
vbc /t:winexe /r:System.dll,System.Drawing.dll,System.Windows.Forms.dll,Misc.dll,MathUtil.dll,Rect.dll,ClassRect.dll,InterfaceRect.dll,ClassRectMemento.dll,InterfaceRectMemento.dll,Line.dll,LineMemento.dll,InputBox.dll,DrawArea.dll,PropertyForm.dll Form1.vb
